[package]
name = "signer"
version = "0.1.0"
authors = ["Zura Benashvili <zura.benashvili@gmail.com>"]
edition = "2018"

[dependencies]
crypto = { path = "../crypto" }
types = { path = "../types" }
trezor_api = { path = "../trezor_api" }
thiserror = "1.0.24"
sodiumoxide = "=0.2.6"
