import type { NextPage } from 'next'
import { useState } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import Select from 'react-select'
import styles from '../styles/Home.module.css'
import { login } from '../store/actions/account';
import { Wallet } from "../store/libs/everlib";



const Home: NextPage = () => {
  const [address, setAddress] = useState('');
 const [token, setToken] = useState('');

 const handleSubmit = e => {
   e.preventDefault();
   const data = {
     address,
     token,
   };
   console.log(data);
   
 };
  return (
    <div className={styles.container}>
    <Head>
    <title>EVER TEZOS Bridge</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={styles.main}>
    <h1 className={styles.title}>
    Welcome to Everangers Bridge!
    </h1>


    <div>
    <form action="" onSubmit={handleSubmit}>
    <input id="address" type="text" autocomplete="address" placeholder="Address" onChange={e => setAddress(e.target.value)} required />
    <input id="token" type="text" autocomplete="token" placeholder="Number of Tokens" onChange={e => setToken(e.target.value)} required />
    <button type="submit"><p>Send</p></button>
    </form>
    </div>
    </main>

    <footer className={styles.footer}>
    Powered by Everangers
    </footer>
    </div>
  )
}

export default Home
