import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Select from 'react-select'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
    <Head>
    <title>EVER TEZOS Bridge</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={styles.main}>
    <h1 className={styles.title}>
    Welcome to Everangers Bridge!
    </h1>

    <p className={styles.description}>
    Get started exchange

    </p>

    <div>
    <form action="http://www.acme.com/register" method="POST">

    <label for="name">Name</label>
    <input id="name" type="text" autocomplete="name" required />
    <button type="submit">Register</button>
    </form>
    </div>
    </main>

    <footer className={styles.footer}>
    Powered by Everangers
    </footer>
    </div>
  )
}

export default Home
