import type { NextPage } from 'next'
import { useState } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import Select from 'react-select'
import styles from '../styles/Home.module.css'
import TonSDK from '../store/libs/tonclient.js'


const Home: NextPage = () => {
  const [address, setAddress] = useState('');
  const [token, setToken] = useState('');
  const [seed, setSeed] = useState('');

  const handleSubmit = e => {
    e.preventDefault();
    const data = {
      address,
      token,
      seed,
    };
    console.log(data);
    console.log(TonSDK.keyPairFromPhrase("meat alcohol target lyrics aware impose timber trial cash foot improve notable"))

    //const keys = TonSDK.keyPairFromPhrase("meat alcohol target lyrics aware impose timber trial cash foot improve notable")
  };
  return (
    <div>
    <Head>
    <title>EVER TEZOS Bridge</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={styles.main}>
    <h1 className={styles.title}>
    Welcome to Everangers Bridge!
    </h1>


    <div>
    <form action="" onSubmit={handleSubmit}>
    <input id="address" type="text" autocomplete="address" placeholder="Введите Адрес на который хотите перевести" onChange={e => setAddress(e.target.value)} required />
    <input id="token" type="text" autocomplete="token" placeholder="Введите количество токенов для перевода" onChange={e => setToken(e.target.value)} required />
    <input id="seed" type="text" autocomplete="token" placeholder="Введите свою seed фразу" onChange={e => setSeed(e.target.value)} required />
    <button type="submit"><p>Send</p></button>
    </form>
    </div>
    </main>

    <footer className={styles.footer}>
    Powered by Everangers
    </footer>
    </div>
  )
}

export default Home
