[package]
name = "trezor_api"
version = "0.1.0"
authors = ["Zura Benashvili <zura.benashvili@gmail.com>"]
edition = "2018"

[build-dependencies]
protoc-rust = "2.22.0"

[dependencies]
types = { path = "../types" }
protobuf = "2.22.0"
rusb = "0.7.0"
byteorder = "1.4.2"
sodiumoxide = "=0.2.6"
